resources:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: kubeovn-operator-crd-fleet
    namespace: cattle-fleet-system
  spec:
    template:
      spec:
        containers:
        - name: kubeovn-operator-crd-fleet
          image: rancher/fleet:{{ .FleetVersion }}
          command: ["fleet"]
          args:
          - "apply"
          - "kubeovn-operator-crd"
          - "/app"
          volumeMounts:
          - name: config-volume
            mountPath: "/app/fleet.yaml"
            subPath: kubeovn-operator-crd-fleet.yaml
            readOnly: false
        restartPolicy: Never
        volumes:
        - name: config-volume
          configMap:
            name: harvester-fleet-config
        serviceAccount: fleet-controller
        serviceAccountName: fleet-controller
